"""add admin_login_logs and admin_operation_logs tables

Revision ID: 7312c7162448
Revises: 5d6d2f32e7b9
Create Date: 2026-03-18 16:38:57.803100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7312c7162448'
down_revision: Union[str, Sequence[str], None] = '5d6d2f32e7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
