"""initial_baseline

Revision ID: 881b84043f08
Revises: 
Create Date: 2026-03-18 14:36:51.600574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881b84043f08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_permissions', sa.Column('effect', sa.String(length=10), nullable=False, comment='效果：allow=允许，deny=拒绝'))
    op.add_column('admin_role_permissions', sa.Column('priority', sa.Integer(), nullable=False, comment='优先级，数值越大优先级越高'))
    op.create_unique_constraint('uq_role_permission', 'admin_role_permissions', ['role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_permission', 'admin_role_permissions', type_='unique')
    op.drop_column('admin_role_permissions', 'priority')
    op.drop_column('admin_role_permissions', 'effect')
    # ### end Alembic commands ###
