"""add app_error_logs table

Revision ID: f7497b85e984
Revises: 881b84043f08
Create Date: 2026-03-18 16:22:55.268847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7497b85e984'
down_revision: Union[str, Sequence[str], None] = '881b84043f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_error_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='日志ID'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='日志级别: WARNING/ERROR/CRITICAL'),
    sa.Column('message', sa.Text(), nullable=False, comment='日志消息'),
    sa.Column('traceback', sa.Text(), nullable=True, comment='异常堆栈信息'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='请求方法'),
    sa.Column('request_path', sa.String(length=500), nullable=True, comment='请求路径'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='触发异常的用户ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='触发异常的用户名'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='客户端IP地址'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_error_logs_id'), 'app_error_logs', ['id'], unique=False)
    op.create_index(op.f('ix_app_error_logs_is_deleted'), 'app_error_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_app_error_logs_level'), 'app_error_logs', ['level'], unique=False)
    op.create_index(op.f('ix_app_error_logs_request_path'), 'app_error_logs', ['request_path'], unique=False)
    op.create_index(op.f('ix_app_error_logs_user_id'), 'app_error_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_error_logs_user_id'), table_name='app_error_logs')
    op.drop_index(op.f('ix_app_error_logs_request_path'), table_name='app_error_logs')
    op.drop_index(op.f('ix_app_error_logs_level'), table_name='app_error_logs')
    op.drop_index(op.f('ix_app_error_logs_is_deleted'), table_name='app_error_logs')
    op.drop_index(op.f('ix_app_error_logs_id'), table_name='app_error_logs')
    op.drop_table('app_error_logs')
    # ### end Alembic commands ###
